#!/bin/bash
alias step-clean="git stash"
alias step-unclean="git stash pop"
alias step-reset="git pull"
alias step-1="git reset --hard step-1"
alias step-2="git reset --hard step-2"
alias step-3="git reset --hard step-3"
alias step-4="git reset --hard step-4"
alias step-5="git reset --hard step-5"
alias step-6="git reset --hard step-6"
